### ISSUE TITLE
Map type ) expected

### ISSUE THREAD

**Issue by yordis** [robinbentley/vscode-sass-indented#10]
Hey I created a map and for some reason I see: `) expected` and probably because of that I see the second error: `colon expected`

![screen shot 2016-11-16 at 3 51 57 am](https://cloud.githubusercontent.com/assets/4237280/20340600/527957ca-abb0-11e6-98e9-76527259dea5.png)

**Comment by robinbentley** [comment]
Hi Yordis, this has nothing to do with this extension.

If you disable the extension you can still see the issue, also you're working with `.scss` and the extension is for `.sass` (the indented syntax) if you're looking to get better support for `.scss` you might want to have a look at [https://github.com/mrmlnc/vscode-scss](https://github.com/mrmlnc/vscode-scss)

**Comment by yordis** [comment]
@robinbentley sorry mate! I would never expect that :|

**Comment by robinbentley** [comment]
No worries, hope you get to the bottom of it 👍
