### ISSUE TITLE
Hover/Command+Hover broken for & selector

### ISSUE THREAD

**Issue by yordis** [robinbentley/vscode-sass-indented#11]
Notice in the screenshot the selector said `undefined--auto`. Also I think because of this the example next to the selector is wrong as well should be `boa-container__column--auto`

![screen shot 2016-11-16 at 3 59 14 am](https://cloud.githubusercontent.com/assets/4237280/20340771/2e8c762a-abb1-11e6-8da0-151336d61f0b.png)

**Comment by robinbentley** [comment]
Please see my comment on #10
