### ISSUE TITLE
CSS deep selector breaks highlighting

### ISSUE THREAD

**Issue by dotcs** [robinbentley/vscode-sass-indented#12]
**Plugin version: 1.2.1**

The plugin seems to have problems with the [deep selector](https://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/#toc-style-cat).

![image](https://cloud.githubusercontent.com/assets/3976183/20567233/482a8f94-b198-11e6-9095-6886d39a2027.png)

Although the compiled code is working, VSCode does not highlight the code correctly. Any ideas on that?

**Comment by robinbentley** [comment]
Hi,

Your example is `.scss`, this extension is for the indented syntax, `.sass` files. Whilst we do access `.scss` files it's only to find variables for the autocomplete, the syntax highlighting from this extension will not be active for `.scss` files.

Sorry for any confusion, I am considering adding Indented back to the extension to avoid this. If you are looking for better `.scss` support I would recommend looking at this extension. [https://github.com/mrmlnc/vscode-scss](https://github.com/mrmlnc/vscode-scss)

**Comment by dotcs** [comment]
Hi Robin,

Thanks for clarification! For me it wasn't quite clear which part is in charge of the syntax highlighting, since VSCode shows filetype sass which references to this plugin. I thought that this means that syntax highlighting is also done by this plugin. Sorry for my misunderstandings.

Unfortunately the plugin you mentioned doesn't solve the problems either. The syntax highlighting is still broken. :/

But since it isn't a problem of your plugin I'll close this issue.
