### ISSUE TITLE
Feature request: Color Preview

### ISSUE THREAD

**Issue by saintplay** [robinbentley/vscode-sass-indented#14]
It would be awesome if you could view some color box preview, like the built-in .scss support of VSCode.

![image](https://cloud.githubusercontent.com/assets/9372893/21906065/c16db7a8-d8d7-11e6-8251-01657f3ebcf5.png)

**Comment by robinbentley** [comment]
Hey Diego,

It's on my list of things to add, once I get some free time I'll look into it

**Comment by GitLiamuk** [comment]
I too would love this feature, I thought it was Code glitching out at first. Hope you can get this sorted.

**Comment by ManuelSch** [comment]
Any updates on this? Would love to see this in any of the upcoming versions!

**Comment by robinbentley** [comment]
@ManuelSch I still want to do it but still just haven't had the time. There is [Color Highlight](https://marketplace.visualstudio.com/items?itemName=naumovs.color-highlight) available that does all the standard formats (hsla, rgba, hex, etc) and will do Sass variables within the same file, I know that's not ideal but it's a stop gap. I've been using it and I would recommend it for anyone waiting for me to deal with this ^^

This will be included as part of project wide variable completion but I just need to find some time and unfortunately it's not high priority. 😞

**Comment by ManuelSch** [comment]
Thanks for the recommendation, that plugin will do it for now  ;)

**Comment by seriouz** [comment]
The "Color Highlight" plugin is nothing against, the one [build into vs code](https://code.visualstudio.com/updates/v1_16#_color-picker-in-html).
So i am waiting too for @robinbentley to implement a custom one for *.sass files.

Q: Would it be possible to use the new one from vscode and just add a trigger for sass files or something like that?

[![image](https://user-images.githubusercontent.com/4722613/33637508-9cd968aa-da21-11e7-8b0e-8524d0f7952d.png)](https://code.visualstudio.com/updates/v1_16#_color-picker-in-html)
