### ISSUE TITLE
Overwriting extension warning

### ISSUE THREAD

**Issue by ajsb85** [robinbentley/vscode-sass-indented#15]
Hi @robinbentley 

I get a warning message in the DevTools

`Overwriting extension <<.scss>> to now point to mime <<text/x-sass>>`

![image](https://cloud.githubusercontent.com/assets/663460/22061036/83a241fa-dd73-11e6-8c18-23d6e6563d6c.png)

**Comment by robinbentley** [comment]
Thanks Alexander,

I'll have a look at what's coming in 1.9 and see what changes need to be made. Although I'm not seeing the message on linux or macOS installs of `1.9.0-insider`.

If the message stops as insider updates could you please just leave a comment, it might just be caused by a problem in the current build.

**Comment by robinbentley** [comment]
@ajsb85 are you still seeing the message? even after the stable version has been updated to 1.9 I am still yet to have it happen.

**Comment by ajsb85** [comment]
Yes

---

- VSCode Version: Code - Insiders 1.10.0-insider (1c1f82e9722d2fafdbebb7524ac2cc465aafdfb4, 2017-02-09T11:45:48.163Z)
- OS Version: Windows_NT ia32 10.0.15031
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.2|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.5|
|xml|DotJoshJohnson|1.7.0|
|ghlink|dt|0.0.5|
|EditorConfig|EditorConfig|0.3.4|
|Theme-Zenburn|gerane|0.0.3|
|sass-lint|glen-84|0.0.3|
|Angular1|johnpapa|0.1.16|
|vscode-commitizen|KnisterPeter|0.3.5|
|vscode-github|KnisterPeter|0.9.0|
|PowerShell|ms-vscode|0.9.0|
|debugger-for-chrome|msjsdiag|2.5.2|
|vscode-docker|PeterJausovec|0.0.11|
|vscode-versionlens|pflannery|0.12.1|
|gitlink|qezhu|0.2.0|
|sass-indented|robinbentley|1.3.0|
|sharecode|RolandGreim|0.4.0|
|vscode-gtm|s3ramsay|0.2.0|
|sonarqube-inject|silverbulleters|1.1.3|
|language-stylus|sysoev|1.6.0|
|gitflow|vector-of-bool|1.0.0|
|github-detial-comment|wk-j|0.0.9|

**Comment by robinbentley** [comment]
Should be fixed with 3989934e2ad0a50f3589dbc315bf67bd41301508 published to the extension gallery yesterday

**Comment by ajsb85** [comment]
Yes 👌
