### ISSUE TITLE
How does one get indentation to work ?

### ISSUE THREAD

**Issue by asmolenic** [robinbentley/vscode-sass-indented#17]
Hello,

I've downloaded this VS Code extension purely because it states "indented" in its name but I can't seem to find a way to actually indent my SCSS files. If there is a way to format/indent the SCSS files I have not been able to find it.

Or maybe the "indented" part does not actually refer to auto-formatting ?

Thanks!

**Comment by robinbentley** [comment]
Hi, 

The extension has nothing to do with auto-formatting. It's purpose is to add syntax highlighting and basic completion support for the indented version of the Sass syntax. The first line of the readme clearly states...

>VSCode only has built in support for SCSS syntax so I have put this together for people who use the indented syntax.

I would suggest taking a few moments to look at the documentation for extensions before just installing them, authors spend time creating it to help users and to avoid any unnecessary issues such as this one.

**Comment by asmolenic** [comment]
Hi, thanks for replying and sorry for misunderstanding what this extension actually does. I also have to mention that I've put at least a couple of hours into reading just about any piece of information about this extension I could find to clarify the "indented" term (which I personally think is a bit misleading).
Thank you again for your time!

**Comment by robinbentley** [comment]
@asmolenic I'm sorry you feel the naming is misleading, however, this is unfortunately error on your part. Not fully understanding the basics of the language has lead to the confusion.

There is two versions of syntax for Sass, the original *indented* syntax used in `.sass` files and the CSS like syntax used in `.scss` files. The [Official Documentation](http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html) explains this well.

VSCode already has great SCSS support but if you feel like you need something more I would suggest checking out the [SCSS Intellisense](https://github.com/mrmlnc/vscode-scss) extension
