### ISSUE TITLE
Highlighting of @param inside commented line

### ISSUE THREAD

**Issue by WhoAteDaCake** [robinbentley/vscode-sass-indented#18]
Having the @param highlighted when describing the function in comments would help with readability.

/// Function
/// @param {String} does something
/// @param {String}  does something
/// @param {Variable}  does something
/// @return the something

**Comment by robinbentley** [comment]
3ee17d521265f776c7c17edd5a677173e2b9ad32 adds highlighting for params within comment blocks

Will be available when I publish tomorrow.
