### ISSUE TITLE
id selector highlighting problem

### ISSUE THREAD

**Issue by guoyunhe** [robinbentley/vscode-sass-indented#20]
![spectacle w20229](https://cloud.githubusercontent.com/assets/5836790/24752566/1d7337e4-1ad7-11e7-9f2d-287dbe930ff5.png)

The highlight of id selector is wrong when it contains `-` and follows a tag name:

```
nav#header-menu
```

**Comment by robinbentley** [comment]
Thanks, Guo. I'll have a look into it

**Comment by robinbentley** [comment]
9747b43139c7970e786330ce7600b0b63b2edf14 fixes this.

Will be available tomorrow when I publish, thank you for the report
