### ISSUE TITLE
Link to github repo itself from README

### ISSUE THREAD

**Issue by ahmetb** [robinbentley/vscode-sass-indented#22]
VSCode itself makes it impossible to navigate to this repo from plugin info screen. If you add link to the repo from README, it'd be helpful

![image](https://cloud.githubusercontent.com/assets/159209/26089551/9649fb4e-39b3-11e7-8d09-7698aa1424ef.png)

**Comment by robinbentley** [comment]
Thanks for the suggestion, there is a link to create an issue a bit down the readme but I'll add a more predominant link so people can get here easier.

When the extension was created there was no in-app gallery and the site automatically created links to the main repo and issues so there was never a real reason to add them into the readme files.
