### ISSUE TITLE
Syntax highlighting bug

### ISSUE THREAD

**Issue by ahmetb** [robinbentley/vscode-sass-indented#23]
it stops getting the pink color after a while:

![image](https://cloud.githubusercontent.com/assets/159209/26089560/af54d582-39b3-11e7-88ab-c9c0c80fb987.png)

content:

```
@mixin md { // Medium devices (tablets, 768px and up)
    @media (min-width: 768px) {
        @content
    }
}

@mixin lg { // Large devices (desktops, 992px and up)
    @media (min-width: 992px) {
        @content
    }
}

@mixin xl { // Extra large devices (large desktops, 1200px and up)
    @media (min-width: 992px) {
        @content
    }
}

@mixin xxl { // XXL devices (not in bootstrap standard, 1440px and up)
    @media (min-width: 992px) {
        @content
    }
}

```

**Comment by robinbentley** [comment]
Hi Ahmet, thanks for the report but the code example you have posted is `.scss`, this extension only contributes to the intended syntax (`.sass`  files).

This looks to be an issue with the built in `.scss` support, if you add the semis in the highlighting works as expected. I would [open an issue](https://github.com/Microsoft/vscode/issues) with the VSCode team so they can take a look.  

<img width="685" alt="screen shot 2017-05-16 at 09 09 48" src="https://cloud.githubusercontent.com/assets/2156395/26095949/78d79922-3a17-11e7-993c-a96a8600d83a.png">
