### ISSUE TITLE
Indicates CSS3 Grid properties, as "Uknown property"

### ISSUE THREAD

**Issue by Kamilius** [robinbentley/vscode-sass-indented#24]
Trying to use CSS3 Grid with Visual Studio Code and all of them are highlighted as "[scss] Unknown property".

Is there a way to add CSS3 Grid support?

**Comment by robinbentley** [comment]
Hi Oleksandr, 

Could you supply a code sample please. However, if you are getting specific `.scss` errors then it probably isn't related to this extension as it only contributes to `.sass` files

**Comment by robinbentley** [comment]
I'm going to close this because of the lack of information. I will re-open if/when this is supplied.

**Comment by sebazelonka** [comment]
Hi @robinbentley, I get the same error.

```
#wrapper {
    display: grid;
    grid-template-columns: 350px 1fr 1fr 1fr;
    grid-template-rows: auto auto auto;
    height: 100vh;
    overflow: hidden;

    .header {
        grid-column: 1 / 5;
        grid-row-start: 1;
    }
}
````
Here is an screenshot:
![screenshot 2017-07-12 17 09 52](https://user-images.githubusercontent.com/955591/28129971-ce28ae54-670b-11e7-9f5f-db025da5b071.png)

This is not a big deal, but is a regular property, so it will be good if you can fix this.

Thanks!
seba

**Comment by robinbentley** [comment]
@sebazelonka  Hi Seba,

Thank you for the report but those messages are either from the built in `.scss` support or from sass-lint if you have that extension.

As you are using the Scss syntax my extension won't be active when editing `.scss` files, only `.sass`

**Comment by sebazelonka** [comment]
Oh, sorry!
Thanks for your answer :)
