### ISSUE TITLE
SCSS warnings with BEM syntax

### ISSUE THREAD

**Issue by psyked** [robinbentley/vscode-sass-indented#29]
See this issue: https://github.com/sass/libsass/issues/1825 - SCSS selectors with `&--` display errors when they should be valid.

It sounds like this is fixed in the latest version of libsass / node-sass, but I assume this plugin is responsible for the code evaluation, and the version of libsass it uses is out of date? Can this plugin be updated to incorporate the latest version of libsass, or does it depend on something else on my system?

**Comment by robinbentley** [comment]
Hi James,

The extension doesn't do any evaluation or have any interaction with node-sass, it's just the basic highlighting, property autocomplete and snippets.

Errors in the VSCode 'Problems' could be coming from another extension, such as sass-lint if that's present or errors during compilation will be a local/project version of node-sass.

**Comment by psyked** [comment]
Thanks - I'll look into the other extensions in my setup then!
