### ISSUE TITLE
Go to symbol doesnt work...

### ISSUE THREAD

**Issue by mugukamil** [robinbentley/vscode-sass-indented#31]
![e1c6dd2201e436e39233b](https://user-images.githubusercontent.com/4193470/31496905-e01a97ec-af65-11e7-9382-25bf1407f80d.png)

**Comment by robinbentley** [comment]
Hi Kamil, 

This extension doesn't have symbol support at present

**Comment by drewlustro** [comment]
Is there any extension for VSCode that provides indented Sass symbol lookup?

**Comment by robinbentley** [comment]
@drewlustro not that I am aware of. iirc that’s going to involve implementing a language server and node-sass has been pretty funny about that in the past. Could be different now though, I haven’t looked in a while.
