### ISSUE TITLE
code block error

### ISSUE THREAD

**Issue by nella17** [robinbentley/vscode-sass-indented#32]
code
```
=size($w, $h: $w, $bdrs: 0)
  width: $w
  height: $h
  border-radius: $bdrs

=overflow-docx3
  overflow: hidden
  text-overflow: ellipsis
  white-space: nowrap

=flex($a: center, $j: center)
  display: flex
  align-items: $a
  justify-content: $j
```

vscode

<img width="300" alt="vscode-1" src="https://user-images.githubusercontent.com/14134195/31497358-7458a7de-af91-11e7-856f-429febaafe5a.png">
<img width="300" alt="vscode-2" src="https://user-images.githubusercontent.com/14134195/31497359-749784fe-af91-11e7-9fb9-1d216e273bdc.png">

sublime text

<img width="300" alt="sublime-text-1" src="https://user-images.githubusercontent.com/14134195/31497366-785ad2b2-af91-11e7-8895-ca7542daea67.png">
<img width="300" alt="sublime-text-2" src="https://user-images.githubusercontent.com/14134195/31497368-7897a764-af91-11e7-874c-2e604f2ec25c.png">

**Comment by robinbentley** [comment]
Hi Allen,

I believe this is related to the September 2017 updates [here](https://code.visualstudio.com/updates/v1_17#_folding-in-offside-languages). I'll look into it

**Comment by robinbentley** [comment]
Thanks Allen, update will be published this week.
