### ISSUE TITLE
The * selector does not support syntax highlighting.

### ISSUE THREAD

**Issue by mattwaler** [robinbentley/vscode-sass-indented#35]
![screen shot 2018-01-19 at 3 03 40 pm](https://user-images.githubusercontent.com/32300026/35169265-f35d5e7c-fd29-11e7-8bbf-0dc53a7b2969.png)

**Comment by robinbentley** [comment]
Hi @mattwaler 

Thanks for the report. Personally I don't feel this is really an issue but would be happy to accept a PR.
