### ISSUE TITLE
Support for SCSS

### ISSUE THREAD

**Issue by Kcko** [robinbentley/vscode-sass-indented#36]
Is possible to modify this great extension for SCSS? 
I think it would be enough to use a one-way converter from SASS to SCSS,it would be very helpful.

Thx for reply.

**Comment by robinbentley** [comment]
Hi @Kcko, 

I'm not sure I understand what you're asking? VSCode already has good support for SCSS out of the box.

If you could just clarify what you mean I will try and help you as best I can 👍

**Comment by Kcko** [comment]
Hi @robinbentley , at first thx for fast reply.

My request was directed to create ur set of snippet in SASS lang to SCSS lang, because Im using SCSS snippets and ur extension is only for SASS.

I asked for this in VSC github repo , see https://github.com/Microsoft/vscode/issues/41929
If you did this for SCSS it would be great, if not, it does not matter.

I will probably migrate Sublime Text 3 snippets ( https://packagecontrol.io/packages/SCSS%20Snippets%20Complete#selector ) to Visual Code Studio, because your list is good, but is not complete what SCSS/SASS offers :-)

What is your opinion for that?

**Comment by robinbentley** [comment]
Thanks for the clarification @Kcko!

Unfortunately, I've had clashes with the built in support in the past when I allow the extension to be active for `.scss` files so I'd prefer to keep it just to `.sass`. I will update the language support snippets though.

If one doesn't already exist I would suggest you to create a new extension to port those snippets over for `.scss`, if the built in support doesn't have it then I'm sure others will be glad you did. It's very easy to get up and running with extension authoring, MS provide great tools and [instructions here](https://code.visualstudio.com/docs/extensions/overview) 

Good luck! If you need any help at all let me know.

**Comment by Kcko** [comment]
@robinbentley Thx for link, I will try to create my first extension :) and then i wil you show you :) 
in a few weeks, I have a lot of my own work now

Thx for discussion.
