### ISSUE TITLE
Auto-indent does not appear to work when defining selectors

### ISSUE THREAD

**Issue by cscomfort** [robinbentley/vscode-sass-indented#38]
I just installed your plugin--thank you for building it, by the way--and when writing a new selector, auto-indentation does not appear to work when carriage returning to the next line to begin writing properties.

I'm on a Mac running VSC 1.19.2, and Sass 1.4.6. I can confirm that the correct file type association is set to Sass when working on .sass files (or in Vue components with Sass styling).

Am I missing a global configuration setting in VSC, or is this something specific to the installed extension?

Thanks in advance.

**Comment by robinbentley** [comment]
Hi @cscomfort 

Thanks for the report, I've got a feeling this is what #37 is referring to also.

You're not missing anything, it just doesn't do it!. I'll look into it when I get a chance this week. 👍

**Comment by cscomfort** [comment]
Ahh, sorry, I missed that one--should have added to the existing issue. And thanks for the prompt response!

**Comment by robinbentley** [comment]
@cscomfort no worries, this is more coherent and I'm still waiting on info to see if it is the same issue. The former will be closed in favour of this if that's the case.
