### ISSUE TITLE
Add formatting to configuration

### ISSUE THREAD

**Issue by aleshadk** [robinbentley/vscode-sass-indented#39]
Could you please add an indent behaviour to config?

The problem is:

.class[cursor is here]

I press TAB and:
.class {
   [cursor is here after one TAB size]}

I know that it depends on code style, but also there is another problem:
.class {

}[cursor is here]

I press ENTER and:

.class {

}
    [cursor is here after one tab size]

**Comment by robinbentley** [comment]
Hi,

Your example is SCSS. If you're working in a `.scss` file then this extension isn't actually active if you're working in a `.sass` file then you're using the wrong syntax.

Please could you clarify the example and I'll take another look.

**Comment by aleshadk** [comment]
Actualy, I use https://github.com/jonathantneal/precss

With config in User Settings:

"files.associations": {
        "*.pcss": "Sass"
    },

It worked fine before [this commit](https://github.com/robinbentley/vscode-sass-indented/commit/310e0bca795fce570adb28440381f52b3a55ab6a)

**Comment by robinbentley** [comment]
Cheers for getting back, try updating that association to Scss to use the VSCode built in support, as far as I am aware all their Scss support is under that language tag now. That should mean you will get all the syntax highlighting etc and the indentation will act as you would expect with the bracketed syntax.

**Comment by aleshadk** [comment]
Yes, this works, but scss and sass have different syntax, e.g. for mixin, so error highilitings is incorrect

**Comment by robinbentley** [comment]
That will be the difference in definitions between my language file and the VSCode one, I think the one included with this is more complete where the VSCode is mostly just from the CSS definitions.

Ideally the solution to this is create an extension that supports precss properly, by having to use the association you are at the mercy of that language and any changes that might come about, this case being the auto indentation. Does the postcss extension not cover this? I don't really want to be adding to this for languages it isn't intended for
