### ISSUE TITLE
Support for SCSS syntax

### ISSUE THREAD

**Issue by skorenb** [robinbentley/vscode-sass-indented#40]
I like scss style and would be grateful if you implemented that ability :)
or maybe it's already supported and i need just configure it, how?

**Comment by jcrben** [comment]
From the readme:
`VSCode only has built in support for SCSS syntax so I have put this together for people who prefer to use the indented syntax.`

**Comment by robinbentley** [comment]
As @jcrben has pointed out. This extension is only for the indented version of the language. If you require SCSS VSCode does a really good job out of the box, there is also SCSS extensions available but I don't think they will be needed considering the built in support.

Also, my apologies for the late reply. I don't seem to be getting notifications for this repo anymore.
