### ISSUE TITLE
Autocomplete in .sass files is not showing automatically all suggestions for values

### ISSUE THREAD

**Issue by Korlic85** [robinbentley/vscode-sass-indented#43]
when I choose to work in a .sass file format, autocomplete works only for properties but not for values,  to show a suggestion for a value I have to start typing right after a property is selected. 

there is a way to show automatically all the value suggestions for the specific property previously selected ?

**Comment by robinbentley** [comment]
Hi @Korlic85 

Not automatically, no. You can trigger the autocomplete menu by pressing `ctrl+space` when you have finished entering the property though. Bear in mind that whilst this will have the available values for the property it will also include all the sass functions (e.g. `percentage()`, `darken()` etc) too, as they can be used in that context and are part of the auto complete.

**Comment by Korlic85** [comment]
Very nice extension!,  thank you for your prompt response , one last question,  is there any chance in the near future to add this behaviour as an improvement ?

**Comment by robinbentley** [comment]
Thank you. Perhaps, I don't really have a lot of time to work on this at present and there are features in the queue. I will consider it when I get a chance to start making updates again. Hope you can get by with the manual opening for now though 👍
