### ISSUE TITLE
Autocomplete variables and classes 

### ISSUE THREAD

**Issue by mlody1123** [robinbentley/vscode-sass-indented#46]
Hello, before i start description my problem i tell then im a beginner sassy programmer.
So, is there an any options to autocomplete a variables from other file and classes from html file?
When i was trying to do this i have something like that 
![variables](https://user-images.githubusercontent.com/15702769/42467351-f7e66de4-83b1-11e8-948e-eb19dc268774.png)
![classes](https://user-images.githubusercontent.com/15702769/42467358-faf2cb0e-83b1-11e8-9119-ddfc2d1e4e73.png)

**Comment by robinbentley** [comment]
Hi @mlody1123,

Firstly, sorry for the late response.

This extension doesn't currently support global autocompletion, the functionality is planned at some point but I couldn't give you an ETA I'm afraid.
