### ISSUE TITLE
"Format code" command remove all new lines of maps

### ISSUE THREAD

**Issue by NCC1701M** [robinbentley/vscode-sass-indented#5]
When calling the "Format code" on a scss file all new lines of a map are removed.

For example:
This is my map before formatting the code:

``` sass
$my-map: (
      $my-sub-map1: (
           entry1: black,
            entry2: white,
            entry3: blue
      ),
      $my-sub-map1: (
           entry1: blue,
            entry2: black,
            entry3: green
      )
  );
```

And this is it after formatting the code:

``` sass
$my-map: ( $my-sub-map1: ( entry1: black, entry2: white, entry3: blue), $my-sub-map1: ( entry1: blue, entry2: black, entry3: green));
```

With large maps this will be nearly impossible to maintain.

vscode-sass-indented version: 1.1.0

VSCode version: 1.5.2

**Comment by NCC1701M** [comment]
Sorry wrong extension

**Comment by robinbentley** [comment]
Haha no problem, hope you get sorted
