### ISSUE TITLE
Variable not display in SASS file

### ISSUE THREAD

**Issue by dhaval-igex** [robinbentley/vscode-sass-indented#52]
Hi @Sass
In sass file i can't get variables list. But in SCSS file work fine.
i am using VS Code Editor.
Please fix this issue in SASS.
![vscodeissue](https://user-images.githubusercontent.com/30318904/46143527-e1cceb00-c277-11e8-8a12-3b924bdddec2.png)

**Comment by robinbentley** [comment]
Hi @dhaval-igex 

Project wide autocompletion isn't a feature this extension currently offers. The reason it works in SCSS is because that uses a different extension.

I do plan to bring the feature back but it's not completed yet.
