### ISSUE TITLE
Bug with combined media queries

### ISSUE THREAD

**Issue by ncodefun** [robinbentley/vscode-sass-indented#53]
First thanks for this extension !
I'm developing a theme and I hit a bug with the tokens when media queries are combined:

![2018-11-16](https://user-images.githubusercontent.com/35607086/48627324-46581c80-e982-11e8-8cd1-1e5fba7d7731.png)

When I inspect the tokens (inspect with TM scopes) I see that `@media screen` words are linked, so the repeating part without @media doesn't get the correct token.

I was using stylus language extension before (doh!) and it highlights this example correctly –  this must be a good place to look : )

**Comment by robinbentley** [comment]
@ncodefun 

Hi Jośe, sorry it's taken me a while to get back to you.

I'll have a dig into the scopes and see what I can do 👍

**Comment by robinbentley** [comment]
I think i'm going to switch the grammar over to Atom's version https://github.com/robinbentley/vscode-sass-indented/commit/24880c0622a554a432aaddd3f313fee2ca6f683f, this supports the combined media queries and presumably some other updates over the current tmLanguage definitions I'm using.

Just got to do some more checks that everything is supported as I would like. Will look to get this merged shortly.
