### ISSUE TITLE
Disable snippets

### ISSUE THREAD

**Issue by RusyiOleh** [robinbentley/vscode-sass-indented#56]
Is there a way to disable snippets? 
When I type, for example, h1 selector I need to type 'h1', then space (because if I hit Enter immediately autocomplete will turn it to height: 1), then snippets appear, so I can't press enter because it will insert the snippet. So to get to the next line and start type real styles I need to type 'h1', press space, remove space, and then click Enter, which is really annoying.
Thanks

![snippets](https://user-images.githubusercontent.com/13406460/50400392-09f0bb00-078f-11e9-808e-6e445f8e6dc5.gif)

**Comment by robinbentley** [comment]
Adding `"emmet.showSuggestionsAsSnippets": true` to your `settings.json` and then disabling them for `sass` with...
```
"[sass]": {
     "editor.snippetSuggestions": "none",
}
```

_should_ take care of this whilst retaining the ability to expand emmet via tab if needed, presuming `"emmet.triggerExpansionOnTab": true`

I don't actually get the additional snippet pop up after hitting space (`@each` etc), I imagine this is probably a difference between our settings. If you do the above ^^ and it's still not right then let me know what you have in your settings and what other extensions you use so I can have a better chance of replicating.

**Comment by robinbentley** [comment]
Closing due to no response. Will re-open if needs be

**Comment by RusyiOleh** [comment]
Hi, this helped,

"[sass]": {
        "editor.snippetSuggestions": "none",
   }

But without "emmet.showSuggestionsAsSnippets": true . With that setting my autocomplete on tab not working. So just "[sass]": {
        "editor.snippetSuggestions": "none",
   }

Thanks)
