### ISSUE TITLE
The Live Sass compiler dosen't work

### ISSUE THREAD

**Issue by EslamShams** [robinbentley/vscode-sass-indented#59]
Issue Type: <b>Bug</b>

suddenly when i was working on project the live sass compiler stoped.
i try to reinstall it but i can't install it again

Extension version: 1.5.1
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N2840  @ 2.16GHz (2 x 2167)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.89GB (1.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by robinbentley** [comment]
Hi @EslamShams 

This extension doesn't have anything to do with compilation, could you be thinking of [https://github.com/ritwickdey/vscode-live-sass-compiler](https://github.com/ritwickdey/vscode-live-sass-compiler)?
