### ISSUE TITLE
Don't support @-moz-document

### ISSUE THREAD

**Issue by TotooriaHyperion** [robinbentley/vscode-sass-indented#60]
![image](https://user-images.githubusercontent.com/16434801/55059448-f44ea280-50a9-11e9-903e-5ecbcc98e9d3.png)

**Comment by robinbentley** [comment]
Hi @TotooriaHyperion 

You're using SCSS syntax (`.scss` files), this extension is only active for the indented syntax (`.sass` files) You will need to open an issue on the main [VSCode repo](https://github.com/Microsoft/vscode/issues) as Scss support is built into the editor
